const phrases = [
  "Yo nunca lo he hecho sin haber querido.",
  "Yo nunca lo he hecho con mas de una persona en un mismo dia.",
  "Yo nunca me he pensado de tirarme a la madre/padre de un amigo/a.",
  "Yo nunca he querido tirarme al hermano/a de un amigo/a.",
  "Yo nunca me he querido liar con alguien presente.",
  "Yo nunca he tenido fantasias sexuales sobre alguien que no considerase atractivo/a.",
  "Yo nunca lo he hecho a pelo.",
  "Yo nunca he acabado en la boca de alguien/ me han acabado en la boca.",
  "Yo nunca he querido tirarme al novio/a de un amigo/a.",
  "A mi nunca me han pedido que fuese mas lento porque iba demasiado rapido.",
  "Yo nunca he dejado con las ganas a alguien.",
  "A mi nunca me han dejado con las ganas.",
  "Yo nunca he tenido la tipica discusion de \"luces encendidas/ apagadas\".",
  "Yo nunca me he encontrado un pelo en la boca tras hacer oral.",
  "Yo nunca he puesto los cuernos.",
  "A mi nunca me han puesto los cuernos.",
  "Yo nunca he dudado de mi orientacion sexual.",
  "Yo nunca me he liado con dos personas de distinto sexo en una noche.",
  "Yo nunca me he liado con alguien y me he arrepentido inmediatamente despues.",
  "Yo nunca he tenido sexo por pena.",
  "Yo nunca me he tirado a mi ex.",
  "A mi nunca me han pillado en el acto.",
  "Yo nunca lo he hecho en un lugar publico.",
  "Yo nunca lo he hecho en la cama de una tercera persona.",
  "Yo nunca lo he hecho con mas gente al rededor.",
  "Yo nunca he hecho un trio.",
  "Yo nunca he tenido fantasias sexuales sobre hacer un trio con mi novio/a y otra persona.",
  "Yo nunca me he masturbado con un objeto inanimado.",
  "Yo nunca me he hecho daño a mi mismo al masturbarme.",
  "Yo nunca me he decepcionado al liarme/tirarme a alguien con quien tenia muchas ganas.",
  "Yo nunca he practicado sadomasoquismo o usado objetos relacionados.",
  "Yo nunca he intentado anal pero no salio bien.",
  "Yo nunca he practicado anal por placer.",
  "Yo nunca me he liado/tirado a alguien que tenia minimo 5 años mas que yo.",
  "Yo nunca he hecho algo sexual en el colegio/universidad.",
  "A mi nunca me han hecho un chupeton en un lugar poco comun.",
  "Yo nunca he intentado emborrachar a alguien para liarme con esa persona.",
  "Yo nunca he visto porno con otra persona.",
  "Yo nunca me he grabado con alguien en la cama.",
  "Yo nunca me he masturbado con una pelicula que no fuese pornografica.",
  "Yo nunca he tenido un gatillazo.",
  "Yo nunca lo he hecho con la regla.",
  "A mi nunca me han meado encima.",
  "Yo nunca lo he hecho disfrazado para satisfacer algun morbo.",
  "Yo nunca me he liado con el chico/a con quien estaba intentando ligar un amigo/a.",
  "Yo nunca me lo he tragado.",
  "Yo nunca me he excitado en un momento muy poco apropiado.",
  "A mi nunca se me ha roto el condon.",
  "Yo nunca he estado un año sin sexo tras haberlo hecho previamente.",
  "Yo nunca me he limpiado el culo tan fuerte, que el papel se rompe y mi dedo indice acaba tocando mi ano.",
  "Yo nunca me he liado con quien está leyendo la pregunta",
  "Yo nunca he sido rechazado por dos o más personas en una noche",
  "Yo nunca he conducido borracho",
  "Yo nunca me he masturbado y no me he lavado las manos después",
  "Yo nunca me he masturbado en grupo",
  "Yo nunca me he liado con el ex novi@ de un amig@",
  "Yo nunca he practicado sexo sin condón",
  "Yo nunca me he liado con la expareja de alguno de los presentes",
  "Yo nunca he atado a mi pareja teniendo sexo",
  "Yo nunca he practicado sexo en el coche",
  "Yo nunca he follado con gente en casa",
  "Yo nunca he fingido un orgasmo",
  "Yo nunca me he masturbado en un sitio público",
  "Yo nunca he tenido resaca",
  "Yo nunca he perreado en una discoteca",
  "Yo nunca se me ha quitado el bañador por accidente",
  "Yo nunca he practicado sexo oral a alguien que acababa de tener relaciones sexuales",
  "Yo nunca he practicado sexo con dos personas distintas en 24h",
  "Yo nunca le he mirado el culo a alguno de los presentes",
  "Yo nunca he practicado sexo encima de un electrodoméstico",
  "Yo nunca he experimentado con mi orientación sexual",
  "Yo nunca he practicado sexo de acampada",
  "Yo nunca he pensado en probar el semen",
  "Yo nunca he fardado de haber practicado sexo con alguien",
  "Yo nunca me he avergonzado de haber tenido relaciones sexuales con alguien",
  "Yo nunca he probado alguna droga dura",
  "Yo nunca he pensado que la persona de al lado es muy sexy",
  "Yo nunca me he depilado las partes íntimas para luego no acabar follando",
  "Yo nunca he practicado sexo con alguien 4 años mayor que yo",
  "Yo nunca he apagado la luz del pasillo y he ido corriendo a mi habitación",
  "Yo nunca me he reído en un funeral",
  "Yo nunca he vomitado mientras besaba a alguien",
  "Yo nunca he masturbado a mi perro",
  "Yo nunca me he masturbado con un personaje ficticio",
  "Yo nunca me he puesto cachondo por alguien de mi mismo sexo",
  "Yo nunca he escupido durante el sexo",
  "Yo nunca me he salpicado durante una paja",
  "Yo nunca me han pillado masturbándome",
  "Yo nunca he pensado en follarme a una prima",
  "Yo nunca he llorado por mi ex",
  "Yo nunca me he salpicado en la cara al masturbarme",
  "Yo nunca he fardado de mis músculos al ligar",
  "Yo nunca he fardado de mi enorme polla al ligar",
  "Yo nunca he querido follarme a alguno de los presentes",
  "Yo nunca me he corrido en un mueble",
  "Yo nunca me he hecho una paja viendo Instagram",
  "Yo nunca me he hecho pasar por amigo gay para intentar pillar",
  "Yo nunca le he hecho una paja a alguno de los presentes",
  "Yo nunca he creído que soy muy feo",
  "Yo nunca le he metido el dedo por el culo a alguien",
  "Yo nunca he chupado el sobaco de otra persona",
  "Yo nunca he pensado en probar la regla",
  "Yo nunca he empotrado a la tía/tío y le he hecho sangre",
  "Yo nunca me he alegrado de la muerte de alguien",
  "Yo nunca he pensado que alguno de los presentes es penoso",
  "Yo nunca he pensado que soy el puto amo",
  "Yo nunca he pensado que alguno de los presentes huele muy mal",
  "Yo nunca me he roto el frenillo",
  "Yo nunca he preferido jugar a la play que follar",
  "Yo nunca he preferido una mamada a follar",
  "Yo nunca he sido pagafantas para nada",
  "Yo nunca he pensado en follarme a una de 6 años menos",
  "Yo nunca he pensado en comerme una polla (los tíos) y un coño (las tías)",
  "Yo nunca he soñado que mutilaba a gente",
  "Yo nunca he pensado que alguno de los presentes es un fantasma",
  "Yo nunca he pensado que alguno de los presentes es un lameculos",
  "Yo nunca he visto a mis padres follando",
  "Yo nunca he fantaseado con follarme a una vecina",
  "Yo nunca me he masturbado pensando en alguno de los presentes",
  "Yo nunca he mentido en este yo nunca (si lo has hecho te haces un puto Hidalgo entero gilipollas)",
  "Yo nunca he tenido un sueño erótico con alguno de los presentes",
  "Yo nunca he pensado que alguno de los presentes la tiene como un camión",
  "Yo nunca he pensado que algunas de las presentes tiene un coño feo",
  "Yo nunca he pensado que alguno de los presentes la tiene muy chica",
  "Yo nunca me he llevado una desilusión (sexualmente hablando) con alguno de los presentes",
  "Yo nunca me han dejado con los huevos bien gordos",
  "Yo nunca he tenido el coño bien mojado solo liándome",
  "Yo nunca he dejado algún moratón durante el sexo",
  "Yo nunca he meado en casa de alguno en un sitio distinto al baño",
  "Yo nunca he dicho de quedar más tarde para hacerme una paja",
  "Yo nunca he quedado más temprano para hacerme a una antes que otros",
  "Yo nunca me he emborrachado a base de tinto de verano",
  "Yo nunca me he quedado más de una hora fumado mirando a un punto fijo",
  "Yo nunca he soñado con mi ex",
  "Yo nunca he llorado por algún defecto físico",
  "Yo nunca he llorado por sacar menos que un sobresaliente",
  "Yo nunca me he empalmado viendo culos en la clase",
  "Yo nunca he sido cortito y no he pillado que estaban tonteando conmigo",
  "Yo nunca he rechazado follar por pura pereza",
  "Yo nunca he inventado un \"coño artificial\" para masturbarme",
  "Yo nunca he mandado fotos de mi prepucio",
  "Yo nunca he tenido pelos entre los dientes después de chuparlo/a",
  "Yo nunca he pensado que a alguno de los presentes se le daría muy bien ser puta/yigolo",
  "Yo nunca he probado el pienso de gato/perro",
  "Yo nunca me han ofrecido un trío/cuarteto",
  "Yo nunca me he comido más de 20000 kcal en un día",
  "Yo nunca he visto Karmaland",
  "Yo nunca he buscado japonesas/es en porno",
  "Yo nunca he buscado negras/os en porno",
  "Yo nunca me ha dado envidia los trabucos de los actores porno",
  "Yo nunca he fantaseado con que un actor/triz me follase muy duro",
  "Yo nunca he comido cosas azucaradas para que mi semen supiese bien",
  "Yo nunca he buscado maneras para agrandar mi pene",
  "Yo nunca me he corrido sin que me tocasen abajo",
  "Yo nunca he pensado que estaba embarazada/he embarazado a alguien",
  "Yo nunca he practicado sexo anal",
  "Yo nunca he tenido que esconder un chupetón",
  "Yo nunca he tenido celos de alguien aquí presente",
  "Yo nunca he escondido mi última conexión en WhatsApp",
  "Yo nunca me he masturbado más de 4 veces en 24h",
  "Yo nunca me he olido las manos después de rascarme las partes íntimas",
  "Yo nunca he practicado sexo en casa de un amigo o conocido",
  "Yo nunca le he mirado el culo a alguno de los presentes",
  "Yo nunca he tropezado en público",
  "Yo nunca he mentido sobre mi tamaño de polla",
  "Yo nunca me he imaginado el tamaño del pene de un amigo",
  "Yo nunca he enviado fotos en bolas",
  "Yo nunca he pensado que alguno de los presentes necesita un polvo urgentemente",
  "Yo nunca he recibido sexo oral sin estar depilad@",
  "Yo nunca me he liado con alguien al menos 3 años mayor",
  "Yo nunca he practicado sexo en la calle",
  "Yo nunca he eructado mientras estaba besándome con alguien",
  "Yo nunca me he liado con la pareja de alguno de los presentes",
  "Yo nunca he ido borracho a clase",
  "Yo nunca he practicado sexo en el baño de una discoteca",
  "A mí nunca me han pillado masturbándome",
  "Yo nunca me he masturbado con alguien al lado",
  "Yo nunca he besado a dos o más de los presentes",
  "Yo nunca he evitado cagar durante días cuando me iba a campamentos de viaje",
  "Yo nunca he tenido fantasías con algún profesor",
  "Yo nunca le he chupado el pie a alguien",
  "Yo nunca he insultado a un profesor",
  "Yo nunca besaría a alguien aquí presente",
  "Yo nunca he enseñado las tetas en un concierto",
  "Yo nunca he pensado que soy muy bueno practicando sexo oral",
  "Yo nunca me he liado con alguien de mi mismo sexo",
  "Yo nunca he pensado que alguno de los presentes no llegará a nada en la vida",
  "Yo nunca he pensado que alguno de los presentes huele mal",
  "Yo nunca he ido colocado a clase",
  "Yo nunca me he masturbado porque me aburría",
  "Yo nunca he practicado sexo en el bosque",
  "Yo nunca me he olfateado la axila en público",
  "Yo nunca me he exhibido en webcam",
  "Yo nunca me he liado con más de una persona del mismo grupo de amigos",
  "Yo nunca he practicado sexo oral en la primera cita",
  "Yo nunca he bebido en el colegio o instituto",
  "Yo nunca he cambiado el nombre de un contacto para esconder quién era",
  "Yo nunca he olido mis bragas después de quitármelas",
  "Yo nunca me he masturbado con alguien en la habitación sin que se entere",
  "Yo nunca me he arrastrado por alguien",
  "Yo nunca me he masturbado con el chorro de la ducha",
  "A mí nunca me han puesto los cuernos",
  "Yo nunca he fumado hierba",
  "Yo nunca me he excitado con alguno de los presentes",
  "Yo nunca he intentado ligar en otro idioma",
  "Yo nunca he practicado en una orgía",
  "Yo nunca he hecho/me han hecho un chupetón",
  "Yo nunca he roto unos pantalones por la entrepierna",
  "Yo nunca he practicado sexo en la cocina",
  "Yo nunca he besado que acababa de conocer",
  "Yo nunca he hecho una mamada mientras mi pareja conducía",
  "Yo nunca he vomitado por culpa del alcohol",
  "Yo nunca practicado sexo sin condón",
  "Yo nunca le he dicho te quiero a una persona sin sentirlo",
  "Yo nunca he fingido un orgasmo",
  "Yo nunca he liado con el hermano/hermana de un colega",
  "Yo nunca he bebido de la copa de otro",
  "Yo nunca he vomitado encima de alguien",
  "Yo nunca he despertado a alguien durante el sexo",
  "Yo nunca he follado sin ganas",
  "Yo nunca he sido grabado mientras tenía relaciones sexuales",
  "Yo nunca he tenido una relación abierta",
  "Yo nunca he sido multado por mear en la calle",
  "Yo nunca he practicado sexo en un barco",
  "Yo nunca he practicado sexo con más de 5 personas en mi vida",
  "Yo nunca he pagado por sexo",
  "Yo nunca me han dicho que la tengo pequeña",
  "Yo nunca he sido el último en salir de la discoteca",
  "Yo nunca he cagado en la playa",
  "Yo nunca me he hecho una prueba de embarazo",
  "Yo nunca me he emborrachado con mis padres",
  "Yo nunca he visto a alguien teniendo sexo en un coche",
  "Yo nunca me he masturbado en grupo",
  "Yo nunca me han pillado mis padres fumando",
  "Yo nunca he hecho un concurso de eructos",
  "Yo nunca me he tirado un pedo y le he echado la culpa a otro",
  "Yo nunca he hecho un 69",
  "Yo nunca me he despertado sin saber dónde estaba",
  "Yo nunca he tomado droga para tener sexo",
  "Yo nunca he mentido sobre alguna experiencia sexual",
  "Yo nunca he tenido relaciones con un padre o madre",
  "Yo nunca he practicado sexo con una persona aquí presente",
  "Yo nunca he pensado en matar a alguien",
  "Yo nunca me he masturba en el tuto",
  "Yo nunca he pensado que mis tetas son perfectas",
  "Yo nunca he mentido jugando al yo nunca",
  "Yo nunca lo he robado el paquete de tabaco a un colega",
  "Yo nunca he tenido una relación de más de dos años",
  "Yo nunca me he meado encima en los últimos 5 años",
  "Yo nunca me he masturbado con el móvil como vibrador",
  "Yo nunca he atado a mi pareja teniendo sexo",
  "Yo nunca he pensado en cómo sería probar la regla",
  "Yo nunca me han pillado mis padres borracho",
  "Yo nunca me he tomado la pastilla del día después",
  "Yo nunca he entrado a un club de striptease",
  "Yo nunca he fingido estar malo para no ir al tuto",
  "Yo nunca he utilizado una app para ligar",
  "Yo nunca he acabado follando y no me lo esperaba",
  "Yo nunca he pensado que el tamaño importa",
  "Yo nunca he llevado una faja",
  "Yo nunca he intentado hacer posturas extrañas del Kama Sutra",
  "Yo nunca he stalkeado a alguien aquí presente",
  "Yo nunca he mentido sobre mi nota en un examen",
  "Yo nunca he borrado el historial del navegador para ocultar algo",
  "Yo nunca me he tirado un pedo en la piscina",
  "Yo nunca he hecho un concurso de chupitos",
  "Yo nunca he querido ser del sexo opuesto",
  "Yo nunca he olvidado algo de la noche anterior por el alcohol",
  "Yo nunca me he caído al suelo por la calle",
  "Yo nunca me he metido el dedo por el culo",
  "Yo nunca me he tirado un pedo silencioso",
  "Yo nunca me he rascado el culo y me he olido los dedos",
  "Yo nunca he hecho topless en la playa",
  "Yo nunca me he olvidado de que había quedado con alguien",
  "Yo nunca no he podido beber porque tenía que estudiar al día siguiente",
  "Yo nunca he visto porno con colegas",
  "Yo nunca me he cortado depilándome las partes íntimas",
  "Yo nunca he utilizado algún juguete sexual",
  "Yo nunca he sido multado por ir borracho",
  "Yo nunca me he liado con alguien que tuviera pareja",
  "Yo nunca me he liado con la misma persona que un amig@",
  "Yo nunca he falsificado una firma",
  "Yo nunca he practicado sexo oral con alguien del mismo sexo",
  "Yo nunca me he duchado con alguien",
  "Yo nunca he llamado a alguien por otro nombre durante el sexo",
  "A mí nunca me han masturbado o he masturbado con los pies",
  "Yo nunca he dejado caer mi móvil al WC",
  "Y nunca he vuelto con mi ex",
  "Y nunca he dicho que me encantaba un regalo y después lo he devuelto",
  "Y nunca he fingido amar un grupo de música cuando solo me sé el nombre",
  "Y nunca he escrito a mi ex una noche de fiesta",
  "Y nunca he stalkeado el Instagram del/la ex de mi novi@",
  "Y nunca he abierto a la policía por haber hecho un fiestón en casa",
  "Y nunca me he imaginado siendo del sexo opuesto",
  "Yo nunca he llamado mamá a mi profesora",
  "Yo nunca he perdido un iPhone",
  "Yo nunca he pesado la fruta, le he pegado el ticket y luego he metido más",
  "Yo nunca he mirado el papel después de ir al baño",
  "Yo nunca he pillado a un familiar masturbándose",
  "Yo nunca lo he hecho en el probador de una tienda",
  "Yo nunca lo he hecho en una moto",
  "Yo nunca me he sentido atraído por un familiar",
  "Yo nunca he sido pillado fumado al llegar a casa",
  "Yo nunca he estado esposado",
  "Yo nunca he sido detenido por la policía",
  "Yo nunca he robado algo de más de 100 euros",
  "Yo nunca he tenido sexo con alguien que acababa de conocer",
  "Yo nunca me he masturbado con un objeto extraño",
  "Yo nunca me he masturbado fuera de casa",
  "Yo nunca he hablado por Whatsapp con un amigo mientras estaba en el lavabo",
  "Yo nunca me he sentido atraído por una persona mayor de 40",
  "Yo nunca he robado copas de una discoteca",
  "Yo nunca he hablado mal de una persona de este grupo",
  "Yo nunca he tenido más de tres orgasmos en un día",
  "Yo nunca he sido infiel",
  "Yo nunca he perdido el conocimiento después de beber",
  "Yo nunca me he tropezado por mirar el móvil",
  "Yo nunca he mentido a mis amigos",
  "Yo nunca he mentido a mi pareja",
  "Yo nunca he hecho un baile erótico",
  "Yo nunca he recibido un baile erótico",
  "Yo nunca he fumado en un bong",
  "Yo nunca me he liado con una persona casada",
  "Yo nunca me he vestido con ropa del sexo opuesto",
  "Yo nunca he usado lubricante sexual",
  "Yo nunca he roto la cama durante el sexo",
  "Yo nunca he probado más de 5 posturas durante el sexo",
  "Yo nunca me he emborrachado por la mañana",
  "Yo nunca he probado el cibersexo",
  "Yo nunca he jugado a ser otra persona durante el sexo",
  "Yo nunca he hecho cosas indecentes en el cine",
  "Yo nunca he llorado por una película",
  "Yo nunca he hecho juegos de bondage",
  "Yo nunca he pasado la noche en el cuartelillo",
  "Yo nunca me liaria con alguien presente",
  "Yo nunca he tenido sexo en un lugar público",
  // ... (añade aquí el resto de frases según quieras)
];

const phraseContainer = document.getElementById('phrase-container');
const nextBtn = document.getElementById('nextBtn');
const resetBtn = document.getElementById('resetBtn');



// Copia de las frases para ir sacando sin repetir
let remainingPhrases = [];

// Función para resetear y preparar el array de frases
function resetPhrases() {
  remainingPhrases = [...phrases]; // copia del array original
  phraseContainer.textContent = 'Pulsa el botón para empezar';
}

// Función para obtener una frase aleatoria sin repetir
function getRandomPhraseNoRepeat() {
  if (remainingPhrases.length === 0) {
    return null; // no quedan frases
  }
  // Selecciona índice aleatorio en las frases restantes
  const idx = Math.floor(Math.random() * remainingPhrases.length);
  // Saca la frase y la elimina del array
  const phrase = remainingPhrases.splice(idx, 1)[0];
  return phrase;
}

// Evento botón siguiente
nextBtn.addEventListener('click', () => {
  const phrase = getRandomPhraseNoRepeat();
  if (phrase) {
    phraseContainer.textContent = phrase;
  } else {
    phraseContainer.textContent = '¡Se acabaron las preguntas!';
  }
});

// Evento botón reset
resetBtn.addEventListener('click', () => {
  resetPhrases();
});

// Inicializamos
resetPhrases();

//modal
const rulesBtn = document.getElementById('rulesBtn');
const rulesModal = document.getElementById('rulesModal');
const closeModal = document.getElementById('closeModal');

// Abrir modal al pulsar normas
rulesBtn.addEventListener('click', () => {
  rulesModal.style.display = 'block';
});

// Cerrar modal al pulsar la X
closeModal.addEventListener('click', () => {
  rulesModal.style.display = 'none';
});

// Cerrar modal si se hace clic fuera del contenido
window.addEventListener('click', (e) => {
  if (e.target === rulesModal) {
    rulesModal.style.display = 'none';
  }
});
